steps:
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      - functions
      - deploy
      - gp_disable_billing_cap_cost    
      - --runtime=python37
      - --allow-unauthenticated
      - --trigger-topic=budgets-notifications
      - --region=europe-west1
      - --memory=128MB
    id: "deploying-a-serverless-function"